import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { Navbar } from "@/components/site/Navbar";
import { Footer } from "@/components/site/Footer";
import { Heart, Mountain, Users, Globe, Star, Award } from "lucide-react";

export const Route = createFileRoute("/about")({
  component: AboutPage,
});

const values = [
  {
    icon: Heart,
    title: "Human-first",
    desc: "Every itinerary is crafted by people who have walked the paths themselves — not generated by an algorithm.",
  },
  {
    icon: Mountain,
    title: "Off the beaten track",
    desc: "We go where the maps run out. Dharavu specialises in routes that guidebooks forget.",
  },
  {
    icon: Users,
    title: "Small groups, big bonds",
    desc: "We cap group sizes so you never feel like a tourist. You leave as a traveller — often with lifelong friends.",
  },
  {
    icon: Globe,
    title: "Responsible travel",
    desc: "We partner with local communities, pay fair wages, and leave every destination better than we found it.",
  },
];

const team = [
  {
    name: "Shivam Dahifale",
    role: "Founder & Head of Experiences",
    bio: "Shivam has explored 20+ states across India before turning his obsession into Dharavu. He designs every flagship route personally.",
    emoji: "🎩",
  },
  {
    name: "The Dharavu Crew",
    role: "Ground team & local guides",
    bio: "Our on-ground crew are locals who call these landscapes home. They speak the language, know the shortcuts, and always know the best dal on the route.",
    emoji: "🧭",
  },
];

const stats = [
  { value: "500+", label: "Happy travellers" },
  { value: "30+", label: "Destinations covered" },
  { value: "100%", label: "Bookings fulfilled" },
  { value: "4.9★", label: "Average rating" },
];

function AboutPage() {
  return (
    <div className="relative min-h-screen bg-background">
      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden pt-28 pb-20">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute -top-20 left-1/3 h-96 w-96 rounded-full gradient-aurora opacity-20 blur-3xl" />
          <div className="absolute bottom-0 right-1/4 h-72 w-72 rounded-full gradient-sunset opacity-15 blur-3xl" />
        </div>
        <div className="relative mx-auto max-w-4xl px-4 text-center sm:px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 rounded-full glass px-3 py-1.5 text-xs font-semibold text-muted-foreground"
          >
            <Star className="h-3.5 w-3.5 text-amber-500" />
            Our story
          </motion.div>
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="mt-5 text-5xl font-bold leading-tight tracking-tight sm:text-6xl"
          >
            We are wildly <em className="not-italic gradient-text">curious</em>
            <br />about this world
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mt-6 text-lg text-muted-foreground"
          >
            Dharavu Journeys was born from a simple belief: the best travel experiences
            aren't found in a brochure. They're found when you hand yourself over to
            someone who knows the land — and trusts you enough to take you somewhere real.
          </motion.p>
        </div>
      </section>

      {/* Stats */}
      <section className="mx-auto max-w-5xl px-4 pb-20 sm:px-6">
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          {stats.map((s) => (
            <motion.div
              key={s.label}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              className="rounded-3xl glass p-6 text-center"
            >
              <div className="text-3xl font-bold">{s.value}</div>
              <div className="mt-1 text-xs text-muted-foreground">{s.label}</div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Story */}
      <section className="mx-auto max-w-3xl px-4 pb-20 sm:px-6">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="space-y-5 text-base leading-relaxed text-muted-foreground"
        >
          <h2 className="text-3xl font-bold text-foreground">How Dharavu started</h2>
          <p>
            It started with a missed train in Spiti Valley, a wrong turn in Coorg, and one very
            late-night conversation about why every "travel package" felt the same. Shivam Dahifale
            had been travelling across India for years — not on packaged tours, but alone with a
            rucksack and an embarrassingly optimistic attitude.
          </p>
          <p>
            He kept meeting other travellers with the same frustration: incredible places existed,
            but nobody was offering a way to reach them that didn't feel either dangerously
            under-planned or soullessly over-managed.
          </p>
          <p>
            Dharavu — which loosely translates to <em>"the one who holds firm"</em> — became his
            answer. A travel company that builds curated, thoughtful journeys to places that
            matter, run by people who care about the experience as much as you do.
          </p>
          <p>
            Today, from our base in Vadgaon, Pune, we plan trips across India and beyond — from
            the high Himalayas to the backwaters of Kerala, from the living root bridges of
            Meghalaya to the rann of Kutch. Each route has been walked, tasted, and argued over
            by someone on our team before it becomes available to you.
          </p>
        </motion.div>
      </section>

      {/* Values */}
      <section className="mx-auto max-w-5xl px-4 pb-20 sm:px-6">
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-8 text-3xl font-bold"
        >
          What we believe in
        </motion.h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {values.map((v, i) => (
            <motion.div
              key={v.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="rounded-3xl glass p-6"
            >
              <div className="mb-3 inline-flex h-10 w-10 items-center justify-center rounded-2xl gradient-aurora">
                <v.icon className="h-5 w-5 text-white" />
              </div>
              <h3 className="font-bold">{v.title}</h3>
              <p className="mt-2 text-sm text-muted-foreground">{v.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Team */}
      <section className="mx-auto max-w-5xl px-4 pb-20 sm:px-6">
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-8 text-3xl font-bold"
        >
          The people behind the journeys
        </motion.h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {team.map((member, i) => (
            <motion.div
              key={member.name}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.15 }}
              className="flex gap-4 rounded-3xl glass p-6"
            >
              <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-3xl">
                {member.emoji}
              </div>
              <div>
                <div className="font-bold">{member.name}</div>
                <div className="text-xs text-primary">{member.role}</div>
                <p className="mt-2 text-sm text-muted-foreground">{member.bio}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-5xl px-4 pb-24 sm:px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="relative overflow-hidden rounded-[2.5rem] gradient-sunset p-10 text-center shadow-float"
        >
          <Award className="mx-auto h-10 w-10 text-white/80" />
          <h2 className="mt-4 text-3xl font-bold text-white">Ready to travel with us?</h2>
          <p className="mt-3 text-white/80">
            Browse our curated trips or tell us your dream and we'll build it for you.
          </p>
          <div className="mt-6 flex flex-wrap justify-center gap-3">
            <a
              href="/#trips"
              className="rounded-full bg-white px-6 py-3 text-sm font-bold text-foreground shadow transition hover:scale-105"
            >
              Browse trips
            </a>
            <a
              href="/contact"
              className="rounded-full border border-white/30 bg-white/10 px-6 py-3 text-sm font-semibold text-white backdrop-blur-sm transition hover:bg-white/20"
            >
              Get in touch
            </a>
          </div>
        </motion.div>
      </section>

      <Footer />
    </div>
  );
}
