/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookingPolicyRouteImport } from './routes/booking-policy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPolicyRoute = BookingPolicyRouteImport.update({
  id: '/booking-policy',
  path: '/booking-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/booking-policy'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/profile'
    | '/safety'
    | '/sustainability'
    | '/terms'
    | '/reset-password/$token'
    | '/trips/$slug'
    | '/verify-email/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/booking-policy'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/profile'
    | '/safety'
    | '/sustainability'
    | '/terms'
    | '/reset-password/$token'
    | '/trips/$slug'
    | '/verify-email/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/booking-policy'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/privacy'
    | '/profile'
    | '/safety'
    | '/sustainability'
    | '/terms'
    | '/reset-password/$token'
    | '/trips/$slug'
    | '/verify-email/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookingPolicyRoute: typeof BookingPolicyRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  TripsSlugRoute: typeof TripsSlugRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-policy': {
      id: '/booking-policy'
      path: '/booking-policy'
      fullPath: '/booking-policy'
      preLoaderRoute: typeof BookingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookingPolicyRoute: BookingPolicyRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  TripsSlugRoute: TripsSlugRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
